### ISSUE TITLE
Create load generator

### ISSUE THREAD

**Issue by cihangir** [koding/tf_kafka#2]
same with https://github.com/koding/tf_zookeeper/issues/2 but for kafka.

**Comment by cihangir** [comment]
what is the status on this one?

**Comment by cihangir** [comment]
ping

**Comment by mehmetalisavas** [comment]
@cihangir sorry, when i checked notifications there was hundreads of them. missed it. 
Consumer-producer script is ready for now, but we run them sepearetly because the consumer and procuder are not under the same main func. (in different files.)
